documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**'

cli:
  - changed-files:
      - any-glob-to-any-file:
          - 'cli/**'

plugin:
  - changed-files:
      - any-glob-to-any-file:
          - 'plugin/**'
          - 'feature/**'
          - 'site/**'
          - 'branding/**'

plugin-tests:
  - changed-files:
      - any-glob-to-any-file:
          - 'plugin.tests/**'

plugin-ui:
  - changed-files:
      - any-glob-to-any-file:
          - 'ui/**'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'
